---
- name: install copyq repo (apt)
  become: yes
  apt_repository:
    repo: ppa:hluk/copyq
    state: present
    update_cache: yes

- name: install copyq (apt)
  become: yes
  apt:
    name: "copyq"
    state: latest
