---
- name: install typora key (apt)
  become: yes
  apt_key:
    url: 'https://typora.io/linux/public-key.asc'
    state: present

- name: install typora repo (apt)
  become: yes
  apt_repository:
    repo: deb https://typora.io/linux ./
    state: present

- name: install typora (apt)
  become: yes
  apt:
    name: "typora"
    state: latest
