---
- name: install vscode key (apt)
  become: yes
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/microsoft.asc
    mode: "0644"

- name: install VS Code repo (apt)
  become: yes
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main
    state: present

- name: install VS Code (apt)
  become: yes
  apt:
    name: "code"
    state: latest
