---
- name: install key (apt)
  become: yes
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: install VS Code repo (apt)
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: install VS Code (apt)
  become: yes
  apt:
    name: "code"
    state: latest

- name: install VS Code Insiders (apt)
  become: yes
  apt:
    name: "code-insiders"
    state: latest
