- name: install microsoft key (apt)
  become: yes
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: azure-cli repo (apt)
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main
    state: present
    update_cache: yes

- name: install azure-cli (apt)
  become: yes
  apt:
    name: "azure-cli"
    state: present
