- name: install azlux key (apt)
  become: yes
  get_url:
    url: https://azlux.fr/repo.gpg
    dest: /etc/apt/keyrings/azlux-archive-keyring.gpg
    mode: "0644"

- name: Personnal Azlux's repository
  become: yes
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ bullseye main
    state: present
    update_cache: yes

- name: Install Azlux's repository packages
  apt:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
      - broot
      - duf
      - dog
