- name: certbot repo (apt)
  become: yes
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
    update_cache: yes

- name: install certbot (apt)
  become: yes
  apt:
    name: "certbot"
    state: present
