---
- name: Ensure ~/.config/devenv directory
  file: path=~/.config/devenv state=directory
  tags: dotfiles
- name: Copy tilix.dconf
  copy:
    src: ~/.devenv/dotfiles/tilix.dconf
    dest: ~/.config/devenv/tilix.dconf
  tags: dotfiles
  register: tilix_dconf
- name: Copy mediakeys.dconf
  copy:
    src: ~/.devenv/dotfiles/mediakeys.dconf
    dest: ~/.config/devenv/mediakeys.dconf
  tags: dotfiles
  register: mediakeys_dconf
- name: Copy inputsources.dconf
  copy:
    src: ~/.devenv/dotfiles/inputsources.dconf
    dest: ~/.config/devenv/inputsources.dconf
  tags: dotfiles
  register: inputsources_dconf
- name: Ensure ~/.config/systemd directory
  file: path=~/.config/systemd state=directory
  tags: dotfiles
- name: Ensure ~/.config/systemd/user directory
  file: path=~/.config/systemd/user state=directory
  tags: dotfiles
- name: Start tmux on init
  file:
    src: ~/.devenv/dotfiles/tmux.service
    dest: ~/.config/systemd/user/tmux.service
    state: link
  tags: dotfiles
- name: Enable service tmux and ensure is started
  systemd:
    name: tmux
    state: started
    enabled: yes
    scope: user
  tags: dotfiles
- name: Dotfile ~/.tmux.conf
  file:
    src: ~/.devenv/dotfiles/.tmux.conf
    dest: ~/.tmux.conf
    state: link
  tags: dotfiles
- name: Dotfile ~/.vimrc
  file:
    src: ~/.devenv/dotfiles/.vimrc
    dest: ~/.vimrc
    state: link
  tags: dotfiles
- name: Dotfile ~/.inputrc
  file:
    src: ~/.devenv/dotfiles/.inputrc
    dest: ~/.inputrc
    state: link
  tags: dotfiles
- name: Dotfile ~/.extend.bashrc
  file:
    src: ~/.devenv/dotfiles/.extend.bashrc
    dest: ~/.extend.bashrc
    state: link
  tags: dotfiles
- name: Extend bashrc
  lineinfile:
    path: ~/.bashrc
    regexp: "# extend bashrc"
    insertafter: "EOF"
    line: "[[ -f ~/.extend.bashrc ]] && . ~/.extend.bashrc # extend bashrc"
    state: present
  tags: dotfiles
- name: Local bashrc
  lineinfile:
    path: ~/.bashrc
    regexp: "# local bashrc"
    insertafter: "EOF"
    line: "[[ -f ~/.local.bashrc ]] && . ~/.local.bashrc # local bashrc"
    state: present
  tags: dotfiles
