---
- name: Ensure ~/.config/systemd directory
  file: path=~/.config/systemd state=directory
  tags: dotfiles
- name: Ensure ~/.config/systemd/user directory
  file: path=~/.config/systemd/user state=directory
  tags: dotfiles
- name: Start tmux on init
  file:
    src: ~/.devenv/dotfiles/tmux.service
    dest: ~/.config/systemd/user/tmux.service
    state: link
  tags: dotfiles
- name: Enable service tmux and ensure is started
  systemd:
    name: tmux
    state: started
    enabled: yes
    scope: user
  tags: dotfiles
- name: Dotfile ~/.tmux.conf
  file:
    src: ~/.devenv/dotfiles/.tmux.conf
    dest: ~/.tmux.conf
    state: link
  tags: dotfiles
- name: Dotfile ~/.vimrc
  file:
    src: ~/.devenv/dotfiles/.vimrc
    dest: ~/.vimrc
    state: link
  tags: dotfiles
- name: Dotfile ~/.inputrc
  file:
    src: ~/.devenv/dotfiles/.inputrc
    dest: ~/.inputrc
    state: link
  tags: dotfiles
- name: Dotfile ~/.extend.bashrc
  file:
    src: ~/.devenv/dotfiles/.extend.bashrc
    dest: ~/.extend.bashrc
    state: link
  tags: dotfiles
- name: Extend bashrc
  lineinfile:
    path: ~/.bashrc
    regexp: '# extend bashrc'
    insertafter: 'EOF'
    line: '[[ -f ~/.extend.bashrc ]] && . ~/.extend.bashrc # extend bashrc'
    state: present
  tags: dotfiles
