- name: Download dust
  become: true
  get_url:
    url: https://github.com/bootandy/dust/releases/download/v0.6.2/dust-v0.6.2-i686-unknown-linux-gnu.tar.gz
    dest: /opt/dust-v0.6.2-i686-unknown-linux-gnu.tar.gz
    force: yes
  register: dust_download
- name: Untar dust
  become: true
  unarchive:
    src: /opt/dust-v0.6.2-i686-unknown-linux-gnu.tar.gz
    dest: /opt
  when: dust_download.changed
- name: Create a symbolic link for dust
  ansible.builtin.file:
    src: /opt/dust-v0.6.2-i686-unknown-linux-gnu/dust
    dest: ~/.local/bin/dust
    state: link
