- name: Add fish repository
  become: yes
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
    update_cache: yes
- name: Install basic Ubuntu packages
  become: true
  apt:
      name: fish
