- name: Install basic Ubuntu packages
  apt:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
    - aptitude
    - build-essential
    - cmake
    - curl
    - font-manager
    - htop
    - libssl-dev
    - nfs-kernel-server
    - nfs-common
    - openvpn
    - powerline
    - python-argcomplete
    - telnet
    - tmux
    - traceroute
    - ttf-mscorefonts-installer
    - unrar
    - vagrant
    - wget
    - whois
    - wmctrl
    - xclip
    - xtrlock
    - zsh
    - zsh-antigen
