- name: Install basic Ubuntu packages
  apt:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
    - aptitude
    - apt-transport-https
    - binutils-dev
    - build-essential
    - ca-certificates
    - certbot
    - cmake
    - curl
    - debhelper
    - dpkg-dev
    - htop
    - gnupg
    - libgcrypt20-dev
    - libssl-dev
    - libyajl-dev
    - libboost-all-dev
    - libcurl4-openssl-dev
    - libexpat1-dev
    - libcppunit-dev
    - lsb-release
    - nfs-kernel-server
    - nfs-common
    - openvpn
    - pkg-config
    - software-properties-common
    - telnet
    - tmux
    - traceroute
    - ttf-mscorefonts-installer
    - unrar
    - wget
    - whois
    - wmctrl
    - xclip
    - xtrlock
    - zlib1g-dev
