---
- name: Create ~/.fonts directory
  file: path=~/.fonts state=directory
- name: Create ~/.config/fontconfig/conf.d directory
  file: path=~/.config/fontconfig/conf.d state=directory
- name: Download PowerlineSymbols.otf font
  get_url: url=https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf dest=~/.fonts/
  register: powerlinesymbols_font
- name: Download 10-powerline-symbols.conf
  get_url: url=https://raw.github.com/Lokaltog/powerline/develop/font/10-powerline-symbols.conf dest=~/.config/fontconfig/conf.d/
- name: Refresh font cache
  shell: /usr/bin/fc-cache -vf ~/.fonts
  when: powerlinesymbols_font.changed
